Service:
  RegionId: cn-hangzhou
  DeployType: ros
  TenantType: SingleTenant
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: sp-
    SupplierDeployMetadata:
      UserType: Aliyun
      RoleName: ${RoleName}
      SupplierTemplateConfigs:
        - Name: 单机版
          Url: 'ros_templates/template.yaml'
          AllowedRegions:
            - cn-hangzhou
          PredefinedParameters:
            - Name: 低配版
              Description: 该套餐采用了2vCPU 4GB内存的ECS实例
              Parameters:
                EcsInstanceType: ['ecs.u1-c1m2.large']
              Type: Normal
              OrderList:
                - EcsInstanceType
            - Name: 基础版
              Description: 该套餐采用了4vCPU 8GB内存的ECS实例
              Parameters:
                EcsInstanceType: ['ecs.u1-c1m2.xlarge']
              Type: Normal
              OrderList:
                - EcsInstanceType
            - Name: 高配版
              Description: 该套餐采用了8vCPU 16GB内存的ECS实例
              Parameters:
                EcsInstanceType: ['ecs.u1-c1m2.2xlarge']
              Type: Normal
              OrderList:
                - EcsInstanceType
          HiddenParameterKeys:
            - EcsInstanceType
            - VpcId
            - VSwitchId
            - ZoneId
          ParameterMappings:
            - ParameterKey: RegionId
              ParameterMappingKeys:
                - VpcId
                - ZoneId
                - VSwitchId
              ParameterValueMapping:
                cn-hangzhou:
                  Parameters:
                    VpcId: ${VpcId}
                    ZoneId: ${ZoneId}
                    VSwitchId: ${VSwitchId}
      FileArtifactRelation:
        '{{ computenest::file::springboot }}':
          ArtifactId: ${Artifact.Artifact_1.ArtifactId}
          ArtifactVersion: ${Artifact.Artifact_1.ArtifactVersion}
    TemplateConfigs:
      - Name: 单机版
        ArchitectureDiagramUrl: 'docs/architecture.png'
    NetworkMetadata:
      EnablePrivateVpcConnection: false
  ServiceType: managed
  IsSupportOperated: true
  PolicyNames: AliyunComputeNestPolicyForOperation
  OperationMetadata:
    ModifyParametersConfig:
      - TemplateName: 单机版
        Operation:
          - Name: 变配套餐
            Description: 变配套餐
            Type: Custom
            SupportPredefinedParameters: true
            EnableLogging: false
    StatusOperationConfigs:
      - TemplateName: 单机版
        DeployScene: ECS
        SupportOperations:
          - Start
          - Stop
          - Restart
  UpgradeMetadata:
    Description: 升级
    SupportRollback: true
    SupportUpgradeFromVersions: [ ]
    UpgradeComponents:
      - Configuration
      - Resource
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: springboot demo
    Image: 'resources/icons/service_logo.png'
    Name: SpringBoot单机托管版
  ShareType: Public
  ApprovalType: Manual
Artifact:
  Artifact_1:
    ArtifactType: File
    ArtifactName: SpringBootPackage
    Description: 这是一个使用SpringBoot的测试包
    ArtifactProperty:
      RegionId: cn-hangzhou
      Url: 'resources/artifact_resources/file/package.tgz'